version: 0.1

phases:
  build:
    commands:
      - ./gradlew assemble
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - app/build/outputs/apk/app-debug.apk
